/* Live phone positioning: all state is ephemeral and device-local. */
'use strict';
const $=id=>document.getElementById(id),R=6378137,deg=Math.PI/180,rad=180/Math.PI;
const state={running:false,watch:null,timer:null,map:null,puck:null,ring:null,trace:null,gps:null,fixTime:0,estimated:null,estimateTime:0,lastCourse:null,lastSpeed:null,lastAccuracy:null,locationError:null,motion:false,motionSeen:false,gyroSeen:false,orientationSeen:false,motionAsked:false,motionDenied:false,orientationDenied:false,manualGapUntil:0,gapStarted:0,drift:0,unreliable:false,heading:null,headingTime:0,follow:true,lastGpsPoint:null,pendingGps:null,tilesLoaded:false};
const map=L.map('map',{zoomControl:false,attributionControl:true,preferCanvas:true}).setView([0,0],2);
state.map=map;L.control.zoom({position:'topright'}).addTo(map);
const tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap contributors</a>'});
map.on('dragstart zoomstart',()=>{state.follow=false});
const icon=kind=>L.divIcon({className:'',html:`<div class="puck ${kind}"></div>`,iconSize:[18,18],iconAnchor:[9,9]});
function setStatus(text,level='normal',message=''){const e=$('status');e.textContent=text;e.parentNode.className='eyebrow '+(level==='normal'?'':level);if(message)$('message').textContent=message}
function bearing(a,b){const l1=a[0]*deg,l2=b[0]*deg,dl=(b[1]-a[1])*deg;return (Math.atan2(Math.sin(dl)*Math.cos(l2),Math.cos(l1)*Math.sin(l2)-Math.sin(l1)*Math.cos(l2)*Math.cos(dl))*rad+360)%360}
function distance(a,b){const dlat=(b[0]-a[0])*deg,dlon=(b[1]-a[1])*deg,aa=Math.sin(dlat/2)**2+Math.cos(a[0]*deg)*Math.cos(b[0]*deg)*Math.sin(dlon/2)**2;return 2*R*Math.asin(Math.sqrt(aa))}
function move(p,meters,course){const theta=course*deg,d=meters/R,lat=p[0]*deg,lon=p[1]*deg;const lat2=Math.asin(Math.sin(lat)*Math.cos(d)+Math.cos(lat)*Math.sin(d)*Math.cos(theta));const lon2=lon+Math.atan2(Math.sin(theta)*Math.sin(d)*Math.cos(lat),Math.cos(d)-Math.sin(lat)*Math.sin(lat2));return [lat2*rad,((lon2*rad+540)%360)-180]}
function showPoint(p,kind,uncertainty){if(!state.puck){state.puck=L.marker(p,{icon:icon(kind),zIndexOffset:200}).addTo(map)}else {state.puck.setLatLng(p);state.puck.setIcon(icon(kind))}const radius=Math.max(5,Math.min(uncertainty||20,2000));if(!state.ring)state.ring=L.circle(p,{radius,color:'#d3b482',weight:1,opacity:.48,fillColor:'#d3b482',fillOpacity:.09,interactive:false}).addTo(map);else {state.ring.setLatLng(p);state.ring.setRadius(radius)}if(!state.trace)state.trace=L.polyline([],{color:'#d3b482',weight:3,opacity:.9}).addTo(map);const line=state.trace.getLatLngs();if(!line.length||distance([line.at(-1).lat,line.at(-1).lng],p)>3){line.push(p);if(line.length>450)line.shift();state.trace.setLatLngs(line)}if(state.follow)map.setView(p,Math.max(16,map.getZoom()),{animate:false})}
function gpsFix(pos){if(!state.running)return;if(state.manualGapUntil>Date.now()){state.pendingGps=pos;return}const c=pos.coords,p=[c.latitude,c.longitude],now=Date.now();if(!p.every(Number.isFinite))return;if(!state.tilesLoaded){tiles.addTo(map);state.tilesLoaded=true}const accuracy=Number.isFinite(c.accuracy)?c.accuracy:null;let speed=Number.isFinite(c.speed)&&c.speed>=0?c.speed:null,course=Number.isFinite(c.heading)?c.heading:null;
// Derive course only from separated, acceptably precise GPS fixes; never use phone-facing as travel heading.
if(state.lastGpsPoint&&accuracy!==null&&accuracy<45&&state.lastGpsPoint.accuracy<45){const delta=(now-state.lastGpsPoint.time)/1000,meters=distance(state.lastGpsPoint.p,p);if(delta>0.7&&delta<25&&meters>Math.max(accuracy,state.lastGpsPoint.accuracy,8)){if(course===null)course=bearing(state.lastGpsPoint.p,p);if(speed===null)speed=meters/delta}}
state.lastGpsPoint={p,time:now,accuracy:accuracy||999};state.gps=p;state.fixTime=now;state.lastAccuracy=accuracy;
if(speed!==null&&speed<70)state.lastSpeed=speed;if(course!==null)state.lastCourse=course;
state.estimated=p;state.estimateTime=now;state.drift=0;state.unreliable=false;showPoint(p,'',accuracy||25);render()}
function gpsError(err){if(!state.running)return;state.locationError=err;render()}
function motionEvent(ev){state.motionSeen=true;const a=ev.acceleration,rr=ev.rotationRate;state.motion=!!(a&&[a.x,a.y,a.z].some(Number.isFinite));state.gyroSeen=!!(rr&&[rr.alpha,rr.beta,rr.gamma].some(Number.isFinite));if(!state.motion&&state.gyroSeen)state.motion=true}
function orientationEvent(ev){state.orientationSeen=true;const hd=Number.isFinite(ev.webkitCompassHeading)?ev.webkitCompassHeading:Number.isFinite(ev.alpha)?(360-ev.alpha)%360:null;if(hd!==null){state.heading=hd;state.headingTime=Date.now()}}
function render(){if(!state.running)return;const now=Date.now(),age=state.gps?(now-state.fixTime)/1000:Infinity,simGap=state.manualGapUntil>now,stale=age>=4||simGap;const delta=state.estimateTime?(now-state.estimateTime)/1000:0;
if(state.gps&&!stale){state.estimated=state.gps;state.estimateTime=now;state.drift=0;showPoint(state.gps,'',state.lastAccuracy||25);$('source').textContent='GPS FIX';$('drift').textContent='No gap';setStatus('GPS POSITION','normal','GPS is updating your position. The circle is your phone’s reported horizontal accuracy, not measured error.')}else if(state.gps){if(state.gapStarted===0)state.gapStarted=simGap?now:state.fixTime;const t=(now-state.gapStarted)/1000;const hasCourse=state.lastCourse!==null&&state.lastSpeed!==null&&state.lastSpeed>=1;
if(hasCourse&&t<=20&&!state.unreliable){const step=Math.max(0,Math.min(5,delta));state.estimated=move(state.estimated||state.gps,state.lastSpeed*step,state.lastCourse);state.estimateTime=now;state.drift=Math.max(state.lastAccuracy||10,10)+Math.max(3,state.lastSpeed*.4)*t+.45*t*t;showPoint(state.estimated,'estimated',state.drift);$('source').textContent='ESTIMATED';$('drift').textContent=`≥${Math.round(state.drift)} m · ${Math.round(t)}s`;setStatus(simGap?'TEST GAP / ESTIMATE':'GPS GAP / ESTIMATE','warning','Estimated from your last GPS speed and travel direction, not an observed location. The shaded circle is an illustrative minimum uncertainty, not measured error.')}else{state.unreliable=true;if(state.estimated)showPoint(state.estimated,'stale',Math.max(state.drift,Math.max(state.lastAccuracy||10,10)+8*t));$('source').textContent='LAST KNOWN FIX';$('drift').textContent=`UNRELIABLE · ${Math.round(t)}s`;setStatus('POSITION UNKNOWN','error',hasCourse?'Prediction stopped after 20 seconds. Wait for GPS to recover; do not navigate by this marker.':'No reliable bus speed or travel heading. Holding your last fix rather than drawing a false route.')}}else{setStatus('WAITING FOR GPS','warning',state.locationError?`Location unavailable: ${state.locationError.message}. Check location access and move outdoors.`:'Waiting for your first GPS position. Keep this page open and allow location access.');$('source').textContent='WAITING';$('drift').textContent='--'}
$('accuracy').textContent=state.lastAccuracy==null?'-- m':`${Math.round(state.lastAccuracy)} m`;$('speed').innerHTML=state.lastSpeed===null?'--<small>km/h</small>':`${Math.round(state.lastSpeed*3.6)}<small>km/h</small>`;
if(state.gps&&!stale)state.gapStarted=0;
if(state.manualGapUntil&&now>=state.manualGapUntil){state.manualGapUntil=0;state.gapStarted=0;state.unreliable=false;if(state.pendingGps){const pending=state.pendingGps;state.pendingGps=null;gpsFix(pending)}}
$('outage').textContent=simGap?`End test (${Math.ceil((state.manualGapUntil-now)/1000)}s)`:'Test GPS gap';$('outage').disabled=!state.gps;
}
async function start(){if(state.running)return;if(!navigator.geolocation){setStatus('UNSUPPORTED','error','This browser cannot provide location. Open the HTTPS site in Safari or Chrome.');return}if(!isSecureContext){setStatus('HTTPS REQUIRED','error','Phone sensors and GPS require the HTTPS site.');return}state.running=true;document.body.classList.add('active');$('more').hidden=false;$('more').setAttribute('aria-expanded','false');state.follow=true;state.locationError=null;$('start').innerHTML='Stop positioning <span aria-hidden="true">×</span>';$('start').classList.add('stop');setStatus('REQUESTING ACCESS','warning','Allow location and motion access when your phone asks. Waiting for the first GPS fix.');
// iOS requires requestPermission() to be invoked immediately in this click gesture, before awaiting.
const mp=typeof DeviceMotionEvent!=='undefined'&&typeof DeviceMotionEvent.requestPermission==='function'?DeviceMotionEvent.requestPermission().catch(()=> 'denied'):Promise.resolve('not-required');
const op=typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function'?DeviceOrientationEvent.requestPermission().catch(()=> 'denied'):Promise.resolve('not-required');
state.motionAsked=true;window.addEventListener('devicemotion',motionEvent);window.addEventListener('deviceorientation',orientationEvent);
state.watch=navigator.geolocation.watchPosition(gpsFix,gpsError,{enableHighAccuracy:true,maximumAge:1000,timeout:18000});state.timer=setInterval(render,1000);const [m,o]=await Promise.all([mp,op]);state.motionDenied=m==='denied';state.orientationDenied=o==='denied';if(state.motionDenied&&!state.gps)setStatus('MOTION DENIED','warning','GPS tracking can still work, but motion was denied. For sensor tests, allow motion access in your browser settings.');render()}
function stop(){state.running=false;document.body.classList.remove('active','expanded');$('more').hidden=true;$('more').setAttribute('aria-expanded','false');if(state.watch!==null)navigator.geolocation.clearWatch(state.watch);if(state.timer)clearInterval(state.timer);state.watch=state.timer=null;window.removeEventListener('devicemotion',motionEvent);window.removeEventListener('deviceorientation',orientationEvent);state.manualGapUntil=0;state.gapStarted=0;state.lastGpsPoint=null;state.pendingGps=null;state.gps=null;state.estimated=null;state.lastSpeed=state.lastCourse=state.lastAccuracy=null;state.drift=0;state.unreliable=false;$('start').innerHTML='Start positioning <span aria-hidden="true">↗</span>';$('start').classList.remove('stop');$('outage').disabled=true;$('outage').textContent='Test GPS gap';$('accuracy').textContent='-- m';$('drift').textContent='--';$('source').textContent='GPS + motion';$('speed').innerHTML='--<small>km/h</small>';setStatus('STOPPED','normal','Positioning stopped. Your route was not saved or uploaded.');if(state.trace){state.trace.remove();state.trace=null}if(state.puck){state.puck.remove();state.puck=null}if(state.ring){state.ring.remove();state.ring=null}}
$('more').addEventListener('click',()=>{const expanded=document.body.classList.toggle('expanded');$('more').setAttribute('aria-expanded',String(expanded));$('more').innerHTML=expanded?'Less <span aria-hidden="true">⌃</span>':'Details <span aria-hidden="true">⌄</span>'});$('start').addEventListener('click',()=>state.running?stop():start());$('outage').addEventListener('click',()=>{if(!state.running||!state.gps)return;if(state.manualGapUntil>Date.now()){state.manualGapUntil=0;state.gapStarted=0;state.unreliable=false;if(state.pendingGps){const pending=state.pendingGps;state.pendingGps=null;gpsFix(pending)}}else{state.manualGapUntil=Date.now()+15000;state.gapStarted=Date.now();state.estimated=state.gps;state.estimateTime=Date.now();state.unreliable=false}render()});$('recenter').addEventListener('click',()=>{state.follow=true;const p=state.estimated||state.gps;if(p)map.setView(p,Math.max(map.getZoom(),16))});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&state.running){if(state.fixTime&&Date.now()-state.fixTime>4000)state.estimateTime=Date.now();render()}});

const fitSheet=()=>{const h=document.querySelector('.sheet').getBoundingClientRect().height;document.documentElement.style.setProperty('--sheet-height',Math.ceil(h)+'px');map.invalidateSize(false)};new ResizeObserver(fitSheet).observe(document.querySelector('.sheet'));fitSheet();
