const assert=require('node:assert/strict'),{Core,rotate,Axis}=require('../phone-fusion.js');let count=0;const test=(name,f)=>{f();count++;console.log('PASS',name)};
const coords=(speed=5,heading=0)=>({latitude:19,longitude:73,accuracy:5,speed,heading});
test('identity device to ENU',()=>assert.deepEqual(rotate({x:1,y:2,z:3},{alpha:0,beta:0,gamma:0}),[1,2]));
test('90 degree yaw rotates east to north',()=>{const z=rotate({x:1,y:0,z:0},{alpha:90,beta:0,gamma:0});assert(Math.abs(z[0])<1e-9);assert(Math.abs(z[1]-1)<1e-9)});
test('tilt excludes vertical component',()=>{const z=rotate({x:0,y:1,z:0},{alpha:0,beta:90,gamma:0});assert(Math.hypot(...z)<1e-9)});
test('constant acceleration kinematics',()=>{const a=new Axis(0,0,1);for(let i=0;i<100;i++)a.predict(1,.01,1);assert(Math.abs(a.p-.5)<1e-9);assert(Math.abs(a.v-1)<1e-9)});
test('GNSS correction reduces covariance',()=>{const a=new Axis(0,0,5),before=a.pp;a.update(1,4);assert(a.pp<before);assert(a.p>0&&a.p<1)});
test('relative orientation rejected',()=>{const c=new Core();assert.equal(c.orient({alpha:0,beta:0,gamma:0,absolute:false},1000),false)});
test('tilted Safari compass rejected',()=>{const c=new Core();assert.equal(c.orient({alpha:0,beta:70,gamma:0,webkitCompassHeading:0,webkitCompassAccuracy:10},1000),false)});
test('level Safari compass accepted',()=>{const c=new Core();assert(c.orient({alpha:0,beta:0,gamma:0,webkitCompassHeading:0,webkitCompassAccuracy:10},1000))});
test('invalid fixes rejected',()=>{const c=new Core();assert.equal(c.fix({...coords(),latitude:NaN},1000),false);assert.equal(c.fix({...coords(),accuracy:50000},1000),false)});
test('missing initial velocity holds position',()=>{const c=new Core();c.fix({...coords(),speed:null,heading:null},1000);for(let t=1100;t<4000;t+=100)c.predict(t);assert.equal(c.position(4000).mode,'held');assert.equal(c.axes[0].p,0)});
test('stale fix cannot rewind state',()=>{const c=new Core();c.fix(coords(),2000);assert.equal(c.fix(coords(),1000),false)});
test('inertial stream changes estimate',()=>{const c=new Core();c.fix(coords(0),1000);for(let t=1010;t<=5000;t+=10){c.orient({alpha:0,beta:0,gamma:0,absolute:true},t);c.motion({x:1,y:0,z:0},{},t)}assert(c.axes[0].p>7.9);assert.equal(c.position(5000).mode,'inertial')});
test('sensor jerk disables inertial mode',()=>{const c=new Core();c.fix(coords(),1000);c.orient({alpha:0,beta:0,gamma:0,absolute:true},1100);assert.equal(c.motion({x:7,y:0,z:0},{},1100),false)});
test('long outage stops propagation',()=>{const c=new Core();c.fix(coords(),1000);for(let t=1100;t<=20000;t+=100)c.predict(t);const p=c.axes[1].p;c.predict(20100);assert.equal(c.axes[1].p,p);assert.equal(c.position(20100).mode,'held')});
test('hidden tab prevents integration',()=>{const c=new Core();c.fix(coords(),1000);c.hidden=true;c.predict(2000);assert.equal(c.axes[1].p,0)});
test('online bias learns from past GNSS targets only',()=>{const c=new Core();c.fix(coords(),1000);for(let j=1;j<=30;j++){for(let k=1;k<=100;k++){const t=1000+(j-1)*1000+k*10;c.orient({alpha:0,beta:0,gamma:0,absolute:true},t);c.motion({x:.2,y:0,z:0},{},t)}c.fix(coords(),1000+j*1000)}assert(c.learnedWindows>=12);assert(c.bias[0]>.1&&c.bias[0]<.2);c.reset();assert.equal(c.learnedWindows,0)});
test('timer coasting advances without motion samples',()=>{const c=new Core();c.fix(coords(),1000);c.predict(2000);assert(c.axes[1].p>0)});
test('accurate separated fixes initialize missing velocity',()=>{const c=new Core();c.fix({...coords(),speed:null,heading:null},1000);c.fix({...coords(),latitude:19+.0002,speed:null,heading:null},3000);assert(c.velocityKnown)});
test('walking without speed initializes over multiple fixes',()=>{const c=new Core();for(let i=0;i<14;i++)c.fix({...coords(),latitude:19+i*1.4/111319,speed:null,heading:null},1000+i*1000);assert(c.velocityKnown);assert(c.axes[1].p>12)});
test('fresh GPS follows when velocity is missing',()=>{const c=new Core();for(let i=0;i<8;i++)c.fix({...coords(),latitude:19+i/111319,speed:null,heading:null},1000+i*1000);assert(Math.abs(c.axes[1].p-7)<.1)});
test('coarse fix is shown but never dead reckoned',()=>{const c=new Core();assert(c.fix({...coords(),accuracy:250},1000));c.predict(2000);assert.equal(c.mode,'held');assert(c.position(2000).radius>=250)});
console.log(JSON.stringify({passed:count,kind:'synthetic unit/replay tests, not physical phone accuracy'}));
