/* Live phone positioning: all state is ephemeral and device-local. */
'use strict';
const $=id=>document.getElementById(id),R=6378137,deg=Math.PI/180,rad=180/Math.PI;
const state={running:false,watch:null,timer:null,map:null,puck:null,ring:null,trace:null,gps:null,fixTime:0,estimated:null,estimateTime:0,lastCourse:null,lastSpeed:null,lastAccuracy:null,locationError:null,motion:false,motionSeen:false,gyroSeen:false,orientationSeen:false,motionAsked:false,motionDenied:false,orientationDenied:false,manualGapUntil:0,gapStarted:0,drift:0,unreliable:false,heading:null,headingTime:0,follow:true,lastGpsPoint:null,pendingGps:null,tilesLoaded:false};
const fusion=new PhoneFusion.Core();
const map=L.map('map',{zoomControl:false,attributionControl:true,preferCanvas:true}).setView([0,0],2);
state.map=map;L.control.zoom({position:'topright'}).addTo(map);
const tiles=L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noopener">OpenStreetMap contributors</a>'});
map.on('dragstart zoomstart',()=>{state.follow=false});
const icon=kind=>L.divIcon({className:'',html:`<div class="puck ${kind}"></div>`,iconSize:[18,18],iconAnchor:[9,9]});
function setStatus(text,level='normal',message=''){const e=$('status');e.textContent=text;e.parentNode.className='eyebrow '+(level==='normal'?'':level);if(message)$('message').textContent=message}
function bearing(a,b){const l1=a[0]*deg,l2=b[0]*deg,dl=(b[1]-a[1])*deg;return (Math.atan2(Math.sin(dl)*Math.cos(l2),Math.cos(l1)*Math.sin(l2)-Math.sin(l1)*Math.cos(l2)*Math.cos(dl))*rad+360)%360}
function distance(a,b){const dlat=(b[0]-a[0])*deg,dlon=(b[1]-a[1])*deg,aa=Math.sin(dlat/2)**2+Math.cos(a[0]*deg)*Math.cos(b[0]*deg)*Math.sin(dlon/2)**2;return 2*R*Math.asin(Math.sqrt(aa))}
function move(p,meters,course){const theta=course*deg,d=meters/R,lat=p[0]*deg,lon=p[1]*deg;const lat2=Math.asin(Math.sin(lat)*Math.cos(d)+Math.cos(lat)*Math.sin(d)*Math.cos(theta));const lon2=lon+Math.atan2(Math.sin(theta)*Math.sin(d)*Math.cos(lat),Math.cos(d)-Math.sin(lat)*Math.sin(lat2));return [lat2*rad,((lon2*rad+540)%360)-180]}
function showPoint(p,kind,uncertainty){if(!state.puck){state.puck=L.marker(p,{icon:icon(kind),zIndexOffset:200}).addTo(map)}else {state.puck.setLatLng(p);state.puck.setIcon(icon(kind))}const radius=Math.max(5,Math.min(uncertainty||20,2000));if(!state.ring)state.ring=L.circle(p,{radius,color:'#d3b482',weight:1,opacity:.48,fillColor:'#d3b482',fillOpacity:.09,interactive:false}).addTo(map);else {state.ring.setLatLng(p);state.ring.setRadius(radius)}if(!state.trace)state.trace=L.polyline([],{color:'#d3b482',weight:3,opacity:.9}).addTo(map);const line=state.trace.getLatLngs();if(!line.length||distance([line.at(-1).lat,line.at(-1).lng],p)>3){line.push(p);if(line.length>450)line.shift();state.trace.setLatLngs(line)}if(state.follow)map.setView(p,Math.max(16,map.getZoom()),{animate:false})}
function gpsFix(pos){if(!state.running)return;const now=Date.now();if(!Number.isFinite(pos.timestamp)||now-pos.timestamp>3000||pos.timestamp>now+1000)return;if(state.manualGapUntil>now){state.pendingGps=pos;return}if(!fusion.fix(pos.coords,pos.timestamp))return;state.gps=[pos.coords.latitude,pos.coords.longitude];state.fixTime=pos.timestamp;state.lastAccuracy=pos.coords.accuracy;state.locationError=null;if(!state.tilesLoaded){tiles.addTo(map);state.tilesLoaded=true}render()}
function gpsError(err){if(!state.running)return;state.locationError=err;render()}
function motionEvent(ev){state.motionSeen=true;state.motion=!!ev.acceleration;state.gyroSeen=!!ev.rotationRate;fusion.motion(ev.acceleration,ev.rotationRate,Date.now())}
function orientationEvent(ev){state.orientationSeen=true;fusion.orient(ev,Date.now())}
function render(){if(!state.running)return;const now=Date.now();fusion.predict(now);const p=fusion.position(now),simGap=state.manualGapUntil>now;if(p){state.estimated=p.point;state.lastSpeed=p.speed;state.drift=p.radius;const live=p.age<3&&!simGap,held=p.mode==='held';showPoint(p.point,live?'':held?'stale':'estimated',p.radius);$('source').textContent=live?'GNSS FILTER':held?'LAST ESTIMATE':p.mode==='inertial'?'GNSS + INERTIAL':'VELOCITY COAST';$('accuracy').textContent=Math.round(state.lastAccuracy)+' m';$('drift').textContent=live?'No gap':held?'HELD / UNRELIABLE':Math.round(p.radius)+' m · '+Math.floor(p.age)+'s';setStatus(live?'GNSS POSITION':held?'POSITION UNKNOWN':simGap?'TEST / '+(p.mode==='inertial'?'INERTIAL':'COAST'):(p.mode==='inertial'?'INERTIAL ESTIMATE':'COAST ESTIMATE'),live?'normal':held?'error':'warning',live?'GNSS corrects a local position/velocity filter. Reported accuracy comes from the phone, not an independent error measurement.':held?'Estimate held. Sensors, initial velocity or gap duration are insufficient. Wait for a fresh GNSS fix.':'Estimated, not observed. '+(p.mode==='inertial'?'Fresh gravity-free acceleration is rotated into East/North using Earth-referenced orientation.':'No usable Earth-aligned inertial stream; only the last velocity is carried forward.')+' The radius is a conservative model, not certified accuracy.');$('speed').innerHTML=(held?'--':Math.round(p.speed*3.6))+'<small>km/h</small>'}else{setStatus('WAITING FOR GNSS','warning',state.locationError?'Location access unavailable. Check permissions and move outdoors.':'Allow location access, move outdoors and keep this page open.');$('source').textContent='WAITING'}
$('sensor-state').textContent=(fusion.lastMotion&&now-fusion.lastMotion<300?'IMU ready':'IMU unavailable')+' · '+(fusion.orientation&&now-fusion.orientation.time<350?'Earth heading':'No Earth heading');$('learning-state').textContent=fusion.learnedWindows>=12?'Bias fit · '+fusion.learnedWindows+' windows':'Learning · '+fusion.learnedWindows+'/12 windows';$('outage').textContent=simGap?'End test ('+Math.ceil((state.manualGapUntil-now)/1000)+'s)':'Test GPS gap';$('outage').disabled=!state.gps;if(state.manualGapUntil&&now>=state.manualGapUntil){state.manualGapUntil=0;state.pendingGps=null;/* Wait for a new fix, never replay a stale held callback. */}}
async function start(){if(state.running)return;if(!navigator.geolocation){setStatus('UNSUPPORTED','error','This browser cannot provide location. Open the HTTPS site in Safari or Chrome.');return}if(!isSecureContext){setStatus('HTTPS REQUIRED','error','Phone sensors and GPS require the HTTPS site.');return}fusion.reset();state.running=true;document.body.classList.add('active');$('more').hidden=false;$('more').setAttribute('aria-expanded','false');state.follow=true;state.locationError=null;$('start').innerHTML='Stop positioning <span aria-hidden="true">×</span>';$('start').classList.add('stop');setStatus('REQUESTING ACCESS','warning','Allow location and motion access when your phone asks. Waiting for the first GPS fix.');
// iOS requires requestPermission() to be invoked immediately in this click gesture, before awaiting.
const mp=typeof DeviceMotionEvent!=='undefined'&&typeof DeviceMotionEvent.requestPermission==='function'?DeviceMotionEvent.requestPermission().catch(()=> 'denied'):Promise.resolve('not-required');
const op=typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function'?DeviceOrientationEvent.requestPermission().catch(()=> 'denied'):Promise.resolve('not-required');
state.motionAsked=true;window.addEventListener('devicemotion',motionEvent);window.addEventListener('deviceorientation',orientationEvent);window.addEventListener('deviceorientationabsolute',orientationEvent);
state.watch=navigator.geolocation.watchPosition(gpsFix,gpsError,{enableHighAccuracy:true,maximumAge:1000,timeout:18000});state.timer=setInterval(render,1000);const [m,o]=await Promise.all([mp,op]);state.motionDenied=m==='denied';state.orientationDenied=o==='denied';if(state.motionDenied&&!state.gps)setStatus('MOTION DENIED','warning','GPS tracking can still work, but motion was denied. For sensor tests, allow motion access in your browser settings.');render()}
function stop(){state.running=false;document.body.classList.remove('active','expanded');$('more').hidden=true;$('more').setAttribute('aria-expanded','false');if(state.watch!==null)navigator.geolocation.clearWatch(state.watch);if(state.timer)clearInterval(state.timer);state.watch=state.timer=null;window.removeEventListener('devicemotion',motionEvent);window.removeEventListener('deviceorientation',orientationEvent);window.removeEventListener('deviceorientationabsolute',orientationEvent);fusion.reset();state.manualGapUntil=0;state.gapStarted=0;state.lastGpsPoint=null;state.pendingGps=null;state.gps=null;state.estimated=null;state.lastSpeed=state.lastCourse=state.lastAccuracy=null;state.drift=0;state.unreliable=false;$('start').innerHTML='Start positioning <span aria-hidden="true">↗</span>';$('start').classList.remove('stop');$('outage').disabled=true;$('outage').textContent='Test GPS gap';$('accuracy').textContent='-- m';$('drift').textContent='--';$('source').textContent='GPS + motion';$('speed').innerHTML='--<small>km/h</small>';setStatus('STOPPED','normal','Positioning stopped. Your route was not saved or uploaded.');if(state.trace){state.trace.remove();state.trace=null}if(state.puck){state.puck.remove();state.puck=null}if(state.ring){state.ring.remove();state.ring=null}}
$('more').addEventListener('click',()=>{const expanded=document.body.classList.toggle('expanded');$('more').setAttribute('aria-expanded',String(expanded));$('more').innerHTML=expanded?'Less <span aria-hidden="true">⌃</span>':'Details <span aria-hidden="true">⌄</span>'});$('start').addEventListener('click',()=>state.running?stop():start());$('outage').addEventListener('click',()=>{if(!state.running||!state.gps)return;if(state.manualGapUntil>Date.now()){state.manualGapUntil=0;state.gapStarted=0;state.unreliable=false;state.pendingGps=null}else{state.manualGapUntil=Date.now()+15000;state.gapStarted=Date.now();state.estimated=state.gps;state.estimateTime=Date.now();state.unreliable=false}render()});$('recenter').addEventListener('click',()=>{state.follow=true;const p=state.estimated||state.gps;if(p)map.setView(p,Math.max(map.getZoom(),16))});document.addEventListener('visibilitychange',()=>{fusion.hidden=document.hidden;if(!document.hidden&&state.running){fusion.lastPredict=Date.now();fusion.lastMotion=0;render()}});

const fitSheet=()=>{const h=document.querySelector('.sheet').getBoundingClientRect().height;document.documentElement.style.setProperty('--sheet-height',Math.ceil(h)+'px');map.invalidateSize(false)};new ResizeObserver(fitSheet).observe(document.querySelector('.sheet'));fitSheet();
